--- # INstallting Webserver
- hosts: server2
  user: test 
  sudo: yes
  tasks:
     - name: Install httpd package
       yum: name==httpd1234 state=installed
       ignore_errors: yes
     - name: Copy indec html file
       copy: src=/home/test/playbook/index.html dest=/var/www/html/index.html
     - name: Start hhtpd service
       service: name=httpd state=started
