--- # INstallting Webserver
- hosts: webserver
  user: test 
  sudo: yes
  tasks:
     - name: Install httpd package
       yum: name=httpd state=installed
       tags:
          - install
     - name: Copy indec html file
       copy: src=/home/test/playbook/index.html dest=/var/www/html/index.html
       tags:
          - copy
     - name: Start hhtpd service
       service: name=httpd state=started
       tags:
          - always
