--- # Adding Variables 
- hosts: '{{hosts}}'
  user: test
  sudo: yes
  vars:
     pkg: httpd
  vars_files:
     - abc.yml
  vars_prompt:
     - name: pkg2
       prompt: Enter Package name
       private: no
  tasks:
    - name: Install httpd package
      yum: name=httpd state=installed
    - name: copy index.html 
      copy: src=/home/test/playbook/index.html dest=/var/www/html/index.html
    - name: start the service
      service: name=httpd state=started
    - name: Install curl package
      yum: name={{pkg1}} state=installed
    - name: Install telnet package
      yum: name={{pkg2}} state=installed
