--- # INstallting Webserver
- hosts: server2
  user: test 
  sudo: yes
  gather_facts: yes
  tasks:
     - name: Install httpd package
       yum: name=httpd state=installed
       when: ansible_os_family == 'Redhat'
     - name: Install Apache package
       apt: name=Apache state=installed
       when: ansible_os_family == 'Debain'
       ignore_errors: yes
     - name: Copy indec html file
       copy: src=/home/test/playbook/index.html dest=/var/www/html/index.html
     - name: Start hhtpd service
       service: name=httpd state=started
